version: "3"

name: chatbot
services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: chatbot_pgvector
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:management
    container_name: chatbot_rabbitmq
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  default:
    driver: bridge
